### ISSUE TITLE
does not work for me

### ISSUE THREAD

**Issue by calogxro** [Futsy/vscode-headerpatterns#2]
VS Code version: 1.60.2

**Comment by Futsy** [comment]
Hey,

Are you running Visual Code as Admin? The plugin needs admin mode to alter the CSS files (and may need a restart sometimes upon changing the patterns - but there should be a prompt for that).

Seems to work alright with me:

![image](https://user-images.githubusercontent.com/2411884/134801440-b3c42cca-82b8-41dd-939a-8b6a201951ec.png)

Are you on Windows or Linux?

**Comment by Futsy** [comment]
Hey, I'm going to assume you're on Ubuntu/Mac. I can't seem to edit the underlying CSS file on ubuntu. I figured it was due to the pathing that it couldn't resolve the file on Ubuntu but it turns out there's something different going on. I'll need quite a bit more time to add the option to do this on non-windows systems (read: around Christmas 😄 ). Will get back to this when I have the time! For now I will add that this extension is Windows only.
