### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by ekritikos** [Futsy/vscode-headerpatterns#3]
It doesn't work on ubuntu 20.04. Vscode version:
![image](https://user-images.githubusercontent.com/30375176/137309129-a6b90fbc-da13-432f-b870-be11b971aa2a.png)

**Comment by Futsy** [comment]
Hey,

Thanks for reporting, I'll try to see if I can add some changes to make it work on Ubuntu :)

**Comment by ekritikos** [comment]
Thanks for looking into that. I m really interested in that extension as I'd like to use the square pattern on the editor and distinguish between lines/columns more easily.

**Comment by Futsy** [comment]
Hey, sorry for the late reply - I can't seem to edit the underlying CSS file on ubuntu. I figured it was due to the pathing that it couldn't resolve the file on Ubuntu but it turns out there's something different going on. I'll need quite a bit more time to add the option to do this on non-windows systems (read: around Christmas 😄 ).

As for the square pattern - while it does help, the lines don't align exactly with the columns and lines so it may only partially solve the issue. Will get back to this when I have the time! For now I will add that this extension is Windows only.
